markdown: rdiscount
highlighter: pygments
permalink: /:year/:month/:day/:title.html
name: "notes"
markdown: rdiscount

author: "vega"
atom-baseurl: "http://ukiyoevega.github.io"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html

